[package]
name = "ml"
version = "0.1.0"
edition = "2021"

[dependencies]
burn = { version = "0.17.0", features = ["wgpu", "autodiff"] }
tokio = { workspace = true }
zip = { version = "3.0.0", features = ["deflate"] }
glam = "0.30.3"