[package]
name = "ml"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
burn = { version = "0.17.0", features = ["wgpu", "autodiff"] }
tokio = { workspace = true }
glam = { version = "0.30.3", features = ["serde"]}