[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
ml = { path = "../ml" }
yew = { version = "0.21", features = ["csr"] }
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "WebGl2RenderingContext", "MouseEvent"] }

[features]
