[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { workspace = true }
yew = { version = "0.21", features = ["csr"] }
web-sys = { version = "0.3", features = [
    "HtmlCanvasElement",
    "Window",
    "Document",
    "Element",
    "HtmlElement",
    "console"
] }
wasm-bindgen-futures = "0.4.50"
wasm-bindgen = "0.2.100"
wgpu = {version = "25.0.0", features = ["webgl", "wgsl", "webgpu"]}
gloo = "0.11.0"

[features]
