[workspace]
resolver = "2"
members = ["backend", "desktop", "frontend", "ml", "ml-cmd"]

[workspace.dependencies]
tokio = { version = "1.42.0", features = ["full"]}
serde = { version = "1.0.219", features = ["derive"] }
log = "0.4.27"
anyhow = "1.0.98"

[profile.dev]
debug = true
## The emulator is not really usable without optims so we force them even for
## debug builds
overflow-checks = true

[profile.release]
debug = false
# Disable parallel code generation. Increases build time but can improve
# performance
codegen-units = 1
lto = true
panic = 'abort'
incremental = false
overflow-checks = false
