[package]
name = "ml-cmd"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
anyhow = { workspace = true }
clap = { version = "4.5.38", features = ["derive"] }
ml = { path = "../ml" }
