[package]
name = "backend"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
axum = { version = "0.8", features = ["macros", "json", "multipart"] }
uuid = { version = "1", features = ["v4"] }
tower-http = { version = "0.6.4", features = ["cors", "trace"] }
