[package]
name = "backend"
edition = "2024"

[dependencies]
axum = { version = "0.8", features = ["macros", "json"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
tower = "0.5.2"
ml = { path = "../ml" }
log = "0.4.27"