[package]
name = "ml"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { workspace = true }
serde = { workspace = true }
burn = { version = "0.17.0", features = ["wgpu", "autodiff"] }
tokio = { workspace = true }