[package]
name = "viewer"
edition.workspace = true
version.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
wgpu.workspace = true
thiserror = { workspace = true }
web-sys = { workspace = true, features = [
    "HtmlCanvasElement"
]}