[package]
name = "db"
version = "0.1.0"
edition = "2024"

[dependencies]
web-cmn = { path = "../web-cmn" }
anyhow = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
surrealdb = { version = "2.3.3", features = ["kv-mem"] }